# Main Window
TITLE = "OpenGS - Map Tool"
WINDOW_SIZE_WIDTH = 1100
WINDOW_SIZE_HEIGHT = 950
VERSION = 0.1

# Province slider
LAND_PROVINCES_MIN = 100
LAND_PROVINCES_MAX = 10000
LAND_PROVINCES_DEFAULT = 3000
LAND_PROVINCES_TICK = 200
LAND_PROVINCES_STEP = 100

# Ocean slider
OCEAN_PROVINCES_MIN = 10
OCEAN_PROVINCES_MAX = 1000
OCEAN_PROVINCES_DEFAULT = 300
OCEAN_PROVINCES_TICK = 20
OCEAN_PROVINCES_STEP = 10

# Land Map Color Code
OCEAN_COLOR = (5, 20, 18)  # RGB


# Image Display
DISPLAY_SIZE_WIDTH = 400
DISPLAY_SIZE_HEIGHT = 400
