from typing import Protocol
import numpy as np
from numpy.typing import NDArray
from PIL import Image


class MapToolProtocol(Protocol):
    """
    API template for the logic modules to interact with the program state(e.g. UI). 
    This avoids exposing the UI Window to logic modules and allows other implementations.
    """

    # Progress
    def start_progress(self) -> None: ...
    def set_progress(self, value: int) -> None: ...

    # Land
    def set_land_image(self, image: Image.Image | None) -> None: ...
    def get_land_image(self) -> Image.Image | None: ...

    # Boundary
    def set_boundary_image(self, image: Image.Image | None) -> None: ...
    def get_boundary_image(self) -> Image.Image | None: ...

    # Terrain
    def set_terrain_image(self, image: Image.Image | None) -> None: ...
    def get_terrain_image(self) -> Image.Image | None: ...

    # Density
    def set_density_image(self, image: Image.Image | None) -> None: ...
    def get_density_image(self) -> Image.Image | None: ...
    def set_edit_density_available(self, available: bool) -> None: ...

    # Territory
    def set_territory_pmap_and_data(self, pmap: NDArray[np.int32], data: list[dict]) -> None: ...
    def get_territory_pmap_and_data(self) -> tuple[NDArray[np.int32], list[dict]]: ...
    def set_cached_masks(self, masks: dict) -> None: ...
    def get_cached_masks(self) -> dict: ...
    def set_territory_image(self, image: Image.Image | None) -> None: ...
    def get_territory_image(self) -> Image.Image | None: ...
    def get_territory_density_strength(self) -> float: ...
    def get_territory_exclude_ocean_density(self) -> bool: ...
    def get_territory_jagged_land(self) -> bool: ...
    def get_territory_jagged_ocean(self) -> bool: ...
    def get_territory_land_density(self) -> int: ...
    def get_territory_ocean_density(self) -> int: ...
    def set_territory_gen_available(self, available: bool) -> None: ...
    def set_territory_export_available(self, available: bool) -> None: ...
    def set_territory_history_export_available(self, available: bool) -> None: ...

    # Province
    def set_province_image(self, image: Image.Image | None) -> None: ...
    def set_province_data(self, data: list[dict] | None) -> None: ...
    def get_province_data(self) -> list[dict] | None: ...
    def get_province_density_strength(self) -> float: ...
    def get_province_exclude_ocean_density(self) -> bool: ...
    def get_province_jagged_land(self) -> bool: ...
    def get_province_jagged_ocean(self) -> bool: ...
    def get_land_province_count(self) -> int: ...
    def get_ocean_province_count(self) -> int: ...
    def set_province_gen_available(self, available: bool) -> None: ...
    def set_province_export_available(self, available: bool) -> None: ...

    # Notifications
    def check_territory_ready(self) -> None: ...
